spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      mvc:
        routes:
          - id: usuarios-service
            uri: http://localhost:8081
            predicates:
              - Path=/usuarios/**
  discovery:
    enabled: false
